### ISSUE TITLE
GRANSAC detail

### ISSUE THREAD

**Issue by amitadhiman** [srinath1905/GRANSAC#2]
Hi,
 Thank you for GRANSAC. It is running successfully on my system.

I want to study GRANSAC in more detail. Could you please give me a link or document to study mainly about GRANSAC.
Thank you

**Comment by drsrinathsridhar** [comment]
Thanks for using GRANSAC. Wikipedia is a good start to learn more about RANSAC.
GRANSAC is just a generic implementation of RANSAC.

https://en.wikipedia.org/wiki/Random_sample_consensus

**Comment by drsrinathsridhar** [comment]
Closing this since it isn't really an issue.
