### ISSUE TITLE
Is there an example for plane fitting?

### ISSUE THREAD

**Issue by oUp2Uo** [srinath1905/GRANSAC#5]
Thanks for your line fitting example, and it works well.

I tried to write a plane fitting program in 3d just like line fitting in 2d.
Unfortunately, I could not do that successfully till now.

If you have ever tried this before, could please show the example to do this?
Thanks.

**Comment by drsrinathsridhar** [comment]
Thanks for using GRANSAC. Here's a gist for a PlaneModel that fits a plane to a bunch of 3D points.
Should work out of the box like LineModel.

https://gist.github.com/drsrinathsridhar/55b491e79404b170683b527823786a02
