### ISSUE TITLE
Point cloud registration?

### ISSUE THREAD

**Issue by antithing** [srinath1905/GRANSAC#6]
Hi, and thank you for making this code available. I am looking for a very fast way to match points between two point clouds, would this lib be suitable?

Is there any example code around for this kind of task?

Thanks again

**Comment by drsrinathsridhar** [comment]
I don't know your exact use case (e.g., how many points you have, what is "fast" enough for you, etc.) GRANSAC uses multiple threads so it should be fairly fast.

I don't have any benchmarks though.

**Comment by antithing** [comment]
Thanks! Would there be any example code around to illustrate how to use GRANSAC for point cloud registration?

**Comment by drsrinathsridhar** [comment]
GRANSAC it self cannot do registration. RANSAC is only an outlier removal method. For registration you will need to use an alignment algorithm. Please see https://stackoverflow.com/questions/29777238/ransac-like-implementation-for-arbitrary-2d-sets

**Comment by antithing** [comment]
I see! I have various ICP methods, what I need is to filter the point cloud matches. So I can pass two point clouds into GRANSAC and return the matches?  Is there any example code for this? (Thanks for your patience)

**Comment by antithing** [comment]
Thank you. So to find correspondences in two clouds, do I create a Model class based on one cloud, and pass it into your code? If you have a minute to point me in the right direction, it would be very much appreciated. Thanks again.

**Comment by drsrinathsridhar** [comment]
Yep, that's a good start. Please see Point2D example. You would need to implement Point3D and add some add a distance measurement metric.
