### ISSUE TITLE
the return type of cv::getTickCount() is int64

### ISSUE THREAD

**Issue by XYZ-qiyh** [srinath1905/GRANSAC#7]
Hello Dr. Srinath Sridhar. 
Thanks for your amazing work GRANSAC, it helps me a lot. 
https://github.com/drsrinathsridhar/GRANSAC/blob/2e715f2914d3cee80b1e566c0c5fd4445d65ed33/examples/LineFittingSample.cpp#L66
As the title says, the return type of `cv::getTickCount()` should be `int64`, according to opencv2/core/core.hpp. Otherwise, we may find the runtime a negative value.  I'm using OpenCV 2.4.10

**Comment by drsrinathsridhar** [comment]
Thanks for pointer. Fixed.
